package net.projecteuler;

public class Problem2 {

    /*
    Each new term in Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public static void main(String[] args) {
        int number1 = 0;
        int number2 = 1;
        int fibonacciNumber = number1 + number2;
        int sum = 0;
        int limit = 4_000_000;

        while(fibonacciNumber<=limit) {
            System.out.println(fibonacciNumber);
           /* if(fibonacciNumber%2 == 0) {
                sum += fibonacciNumber;
            }
            System.out.println("sum is:" +sum);*/
            number1 = number2;
            number2 = fibonacciNumber;
            fibonacciNumber = number1 + number2;


       }

    }
}
